### ISSUE TITLE
Actions-OpenWrt 失败。

### ISSUE THREAD

**Issue by onewrt** [garypang13/Actions-OpenWrt#1]
直接fork了老大的action代码。什么都没有做。点击star开始action。单出错了，共2处，望指点。谢谢
1.Process completed with exit code 错误在：
[ 64%] Building C object libopkg/CMakeFiles/opkg.dir/parse_util.c.o
[ 66%] Building C object libopkg/CMakeFiles/opkg.dir/pkg.c.o
/home/runner/work/Actions-OpenWrt/Actions-OpenWrt/openwrt/build_dir/hostpkg/opkg-2020-01-25-c09fe209/libopkg/pkg.c: In function 'pkg_set_raw':
/home/runner/work/Actions-OpenWrt/Actions-OpenWrt/openwrt/build_dir/hostpkg/opkg-2020-01-25-c09fe209/libopkg/pkg.c:109:58: warning: format '%d' expects argument of type 'int', but argument 5 has type 'size_t {aka long unsigned int}' [-Wformat=]
     fprintf(stderr, "ERROR: truncating field %d <%p> to %d byte",
                                                         ~^
                                                         %ld
             id, val, blob_len(cur));
                      ~~~~~~~~~~~~~                        
[ 67%] Building C object libopkg/CMakeFiles/opkg.dir/pkg_alternatives.c.o

[ 26%] Building C object libbb/CMakeFiles/bb.dir/wfopen.c.o

2.发布出错。提示：Input required and not supplied: repo_token

    TZ: Asia/Shanghai
    FIRMWARE: /home/runner/work/Actions-OpenWrt/Actions-OpenWrt/firmware
##[error]Input required and not supplied: repo_token

**Comment by garypang13** [comment]
需要在对应仓库的settings->secrets中添加个名字为REPO_TOKEN的encrypted secrets
![lala](https://user-images.githubusercontent.com/48883331/75249219-c79e9000-5810-11ea-88b4-cb7a2272a34a.png)

**Comment by garypang13** [comment]
至于另一个错误,有点奇怪,我今天上午都有编译成功,明天再编译一次看看.

**Comment by onewrt** [comment]
好的。感谢。
