### ISSUE TITLE
luci-app-koolproxyR无法安装

### ISSUE THREAD

**Issue by liuran001** [garypang13/Actions-OpenWrt#119]
如题  
<a href="https://sbimg.cn/image/PfveR"><img src="https://wx2.sbimg.cn/2020/08/04/PfveR.png" alt="PfveR.png" border="0" /></a>
图好像加载不了，可以点进去看   https://sbimg.cn/image/PfveR

**Comment by garypang13** [comment]
@liuran001 请更新8.4号的版本

**Comment by liuran001** [comment]
> @liuran001 请更新8.4号的版本

好的
