### ISSUE TITLE
openclash在nginx下使用有问题

### ISSUE THREAD

**Issue by fantasylidong** [garypang13/Actions-OpenWrt#124]
无法修改规则，重新设定节点后再第三步: 修改配置文件那里卡死，是不是nginx反代luci后的权限问题？
因为我在uhttp设置下是可以正常使用openclash的
![image](https://user-images.githubusercontent.com/22582796/90480860-763de080-e163-11ea-8c92-755ab6ef8c5d.png)
或者重新应用配置的时候，出现第五步: 重启 Dnsmasq 程序后然后整个就没反应了

**Comment by fantasylidong** [comment]
![image](https://user-images.githubusercontent.com/22582796/90481333-2a3f6b80-e164-11ea-9c49-fbbf2b5ccc01.png)

**Comment by RAYSphere** [comment]
https://github.com/vernesong/OpenClash/issues/576
