### ISSUE TITLE
你好，这个在我设备上有几个问题

### ISSUE THREAD

**Issue by pyii** [garypang13/Actions-OpenWrt#126]
你好，这个在我设备上（x86)有几个问题，一个是删掉的软件包一重启又自动装回来了。一个是管理页面经常崩（这个还分两种，一种是503，一种是报一溜lua的错，dispatcher.lua啥啥啥的）然后重启后都会好，过一段时候又GG了。还有一个就是登陆的时候明明用户名密码都没错，就是登不进去。

**Comment by pyii** [comment]
好像就uefi版有这些问题？

**Comment by garypang13** [comment]
删掉的软件包一重启又自动装回来这个问题已经修复.
管理页面经常崩这个问题还有待观察
登不进去在刚安装了某些插件的时候可能会出现,请清除浏览器缓存或使用浏览器隐身模式
