### ISSUE TITLE
错误 无法判断固件类型

### ISSUE THREAD

**Issue by laozhou1204** [garypang13/Actions-OpenWrt#127]
**[k2p]** **08.26-openwrt-ramips-mt7621-redmi-ac2100-squashfs-sysupgrade.bin**
![84b0060849916](https://user-images.githubusercontent.com/47948826/91307691-e04c2a80-e7e0-11ea-8afa-60c724044416.png)
![06fbe040579ee](https://user-images.githubusercontent.com/47948826/91307747-ef32dd00-e7e0-11ea-91ac-77cce3e8b14b.png)

**Comment by littlewhitelyw** [comment]
咋解决的 哥们

**Comment by mmdjiji** [comment]
1. 在breed里刷底包固件；
2. 重启路由器，192.168.1.1进入底包固件的系统，账号密码都是root；
3. 在这个底包固件系统里找到系统升级，选择本地文件全能包进行系统升级；
4. 升级结束后就是最后的完整系统。
