### ISSUE TITLE
K2P能不能集成酸酸普拉斯: 正在执行软件包管理器

### ISSUE THREAD

**Issue by laozhou1204** [garypang13/Actions-OpenWrt#128]
安装软件永远卡在 : **正在执行软件包管理器**
![pp343a0c8be7fd5](https://user-images.githubusercontent.com/47948826/91318021-5b1b4280-e7ed-11ea-93f9-c974f650b648.png)

酸酸普拉斯: 好像是安装好一半 服务栏目显示有 打不开

/usr/lib/lua/luci/model/cbi/shadowsocksr/client.lua:15: bad argument #1 to 'upper' (string expected, got nil)
stack traceback:
	[C]: in function 'upper'
	/usr/lib/lua/luci/model/cbi/shadowsocksr/client.lua:15: in function 'callback'
	/usr/lib/lua/luci/model/uci.lua:269: in function 'foreach'
	/usr/lib/lua/luci/model/cbi/shadowsocksr/client.lua:13: in function 'func'
	/usr/lib/lua/luci/cbi.lua:66: in function 'load'
	/usr/lib/lua/luci/dispatcher.lua:1340: in function '_cbi'
	/usr/lib/lua/luci/dispatcher.lua:1023: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:999: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:478: in function </usr/lib/lua/luci/dispatcher.lua:477>

![c4207987d8817](https://user-images.githubusercontent.com/47948826/91318053-640c1400-e7ed-11ea-8fa8-2868329be671.png)

**Comment by garypang13** [comment]
刷最新版试试.
