### ISSUE TITLE
Turbo ACC问题

### ISSUE THREAD

**Issue by CoolZxp** [garypang13/Actions-OpenWrt#135]
开启Turbo ACC中的 软件流量分载 
会导致抖音评论头像加载不出来
还有钉钉日报什么的

**Comment by garypang13** [comment]
应该是DNS的问题,把Turbo ACC中DNS相关的设置都关闭试试,

**Comment by CoolZxp** [comment]
> 应该是DNS的问题,把Turbo ACC中DNS相关的设置都关闭试试,

不是dns的问题 都去软件包里把dns相关的都卸了 不过0909就没这个问题了
