### ISSUE TITLE
为什么酸酸普拉斯不能添加 vless

### ISSUE THREAD

**Issue by huanx9** [garypang13/Actions-OpenWrt#137]
不是9.9编译的K2P吗 为什么vmess协议和vless等协议均不能添加。。

**Comment by garypang13** [comment]
k2p需要另外安装v2ray核心

**Comment by huanx9** [comment]
能否再下次编译K2P的时候 把v2ray核心一同编译进去

**Comment by garypang13** [comment]
@huanx9 v2ray核心太大了,并不是所有人都需要v2ray核心,有很多ssr trojan机场,或自己搭建的trojan,需要的自己去软件库在线安装下比较合理,

**Comment by huanx9** [comment]
雕多拉 14.7MB  大佬的openwrt 编译完才9MB多，  放一个v2ray核心绰绰有余吧，希望大佬好好考虑一下，刚需

**Comment by garypang13** [comment]
@huanx9 是放的下,但是装了v2ray就基本没有空间装其他插件了,在线安装也足够简单,这是兼顾所有人的最佳解决方案.
