### ISSUE TITLE
关于作者编译固件的几个建议

### ISSUE THREAD

**Issue by WROIATE** [garypang13/Actions-OpenWrt#140]
1.在默认编译设置中将所有网卡驱动都集成，毕竟玩x86的软路由的很多都是老机子，有些稀奇古怪的网卡
2.ipv6helper我在编译时发现未勾选，希望能默认集成

以上仅是个人建议，希望对项目有帮助

**Comment by garypang13** [comment]
感谢建议
大部分网卡驱动都集成了的,如果还有未集成的可以反馈.
ipv6helper lean的项目才需要,官方版并不需要的.固件现在默认就有开启ipv6

**Comment by WROIATE** [comment]
> 感谢建议
> 大部分网卡驱动都集成了的,如果还有未集成的可以反馈.
> ipv6helper lean的项目才需要,官方版并不需要的.固件现在默认就有开启ipv6

好的，我自编译是因为我用的一台老电脑需要sky2驱动，我还在network device当中还看到很多的驱动没选，可能会有人和我一样出现老网卡没驱动的现象
