### ISSUE TITLE
请求加个Newifi-D2

### ISSUE THREAD

**Issue by kk3375** [garypang13/Actions-OpenWrt#143]

**Comment by garypang13** [comment]
新3基本快被淘汰了,用的人不多了,

[openwrt-ramips-mt7621-d-team_newifi-d2-squashfs-sysupgrade.zip](https://github.com/garypang13/Actions-OpenWrt/files/5254920/openwrt-ramips-mt7621-d-team_newifi-d2-squashfs-sysupgrade.zip)

这个是我昨天给个群友编译的,

**Comment by kk3375** [comment]
谢谢，我把K2P config的一行换成CONFIG_TARGET_ramips_mt7621_DEVICE_d-team_newifi-d2=y
编译出的固件也能用，就是ssr不知怎么无法保存订阅地址，保存后订阅地址就是空的，也无法单个输入地址

**Comment by garypang13** [comment]
添加地址后点击下

![image](https://user-images.githubusercontent.com/48883331/93764187-4479d700-fc45-11ea-9d72-a417aa5469f7.png)

这个按钮试试
