### ISSUE TITLE
请问插件和内核版本不兼容怎么办

### ISSUE THREAD

**Issue by 1164715233** [garypang13/Actions-OpenWrt#144]
作者的是5.4.65版本，属于开发者插件库里，但是插件库只有最新的5.4.66和其他的，版本号对不上，软件包里面的插件安装不了，显示不兼容，还有其他源么

**Comment by garypang13** [comment]
哪个插件.

**Comment by 1164715233** [comment]
> 哪个插件.

eqos

**Comment by 1164715233** [comment]
好像不止这个插件，很多插件库里的版本都是kernel (= 5.4.66-1-d10f5bcb998e1babf42435a9b8db6350)

**Comment by garypang13** [comment]
@1164715233 好的,是因为固件内核版本低于插件库内核版本的原因,等我编译版最新固件,刷最新固件即可解决.

**Comment by 1164715233** [comment]
kernel	5.4.65-1- c5955e387fba8da28483933b750f6e64，大佬的内核版本是自己做的吗？https://downloads.openwrt.org/里低版本的号也对不上😭

**Comment by 1164715233** [comment]
> @1164715233 好的,是因为固件内核版本低于插件库内核版本的原因,等我编译版最新固件,刷最新固件即可解决.

感谢

**Comment by 1164715233** [comment]
最新的还是不行，c5955e387fba8da28483933b750f6e64版本号不一样不能添加插件→  d10f5bcb998e1babf42435a9b8db6350

**Comment by garypang13** [comment]
嗯嗯, eqos还是装不上,需要编译的时候加上kmod-ifb这个内核模块,下一版加上
大部分主流插件需要的内核模块默认都有编译上的,装不上的可能是漏掉的,或者很不常用的插件.
