### ISSUE TITLE
mount不能挂sata的ntfs硬盘

### ISSUE THREAD

**Issue by bulubula** [garypang13/Actions-OpenWrt#146]
最新的版本mount不能挂sata的ntfs硬盘，选了ntfs-3g还是不行，只能选fuseblk才能挂，但是选了之后是只读的，晕~~
只能装diskman挂，没有问题，但是装diskman又会因为kernel的版本不同不能装，主要是编译的时候把kernel版本后缀的MD5值带进去导致不一样，
用这个命令改了才能装。。。。
sed -i 's/34e5be77dc7693373e6fc41a17d92829/e603d4dc31dbef7fd2d83e7569e8122e/' /usr/lib/opkg/status
然后diskman挂是没有问题，，，但是重启要重新挂，，，不敢改fstab了，，，太难了

大佬帮忙把这些基础性功能再整整把，我太难了

**Comment by garypang13** [comment]
diskman和cifsmount 确实都安装不上,一会我编译个修复版.

**Comment by garypang13** [comment]
mount插件我用的是lean仓库的,直接用他的源码编译的固件能挂ntfs硬盘吗?
我用的是ext4格式,是可以正常挂载,目前手上没有ntfs硬盘,不好测试.
![image](https://user-images.githubusercontent.com/48883331/94343433-bb024480-004a-11eb-9e26-598679130839.png)

**Comment by garypang13** [comment]
刷最新版试试,新版对mount插件做了调整.
