### ISSUE TITLE
新版ddns有问题

### ISSUE THREAD

**Issue by WROIATE** [garypang13/Actions-OpenWrt#147]
运营商列表为空，无法选择运营商
![Snipaste_2020-09-27_14-16-05](https://user-images.githubusercontent.com/44677306/94357517-09a3f300-00cc-11eb-8de5-680db38afab8.png)

**Comment by garypang13** [comment]
https://github.com/openwrt/packages/issues/13495  bug, 等待官方修复,

**Comment by WROIATE** [comment]
了解
