### ISSUE TITLE
无法转发ftp至内网

### ISSUE THREAD

**Issue by WROIATE** [garypang13/Actions-OpenWrt#148]
使用socat转发出现以下情况
![Snipaste_2020-09-27_15-23-05](https://user-images.githubusercontent.com/44677306/94358726-93a48980-00d5-11eb-9ad4-ae482c32f8c8.png)
请教一下如何转发ipv6的ftp至内网nas上

**Comment by garypang13** [comment]
ipv4的ftp能成功吗,我用的IPV4没有问题.

**Comment by WROIATE** [comment]
> ipv4的ftp能成功吗,我用的IPV4没有问题.

ipv4我能转发21端口的，如果我把端口换成别的也不行，同样会出现上面的积极拒绝
比如这种
![Snipaste_2020-09-27_18-54-26](https://user-images.githubusercontent.com/44677306/94363153-e5a7d800-00f2-11eb-8055-6957e1718bed.png)

随带说一下，他的端口的确是转进去了，我这能显示输入登录的信息，但是输入完就会出现上面的这种reset

**Comment by WROIATE** [comment]
我记得原来用lean的好像没这问题，在lienol那也发现过这个情况

**Comment by garypang13** [comment]
我这21或其他端口都可以,如果是其他端口比如1666的话,连接的时候客户端那边的FTP端口记得也要填1666.

**Comment by WROIATE** [comment]
> 我这21或其他端口都可以,如果是其他端口比如1666的话,连接的时候客户端那边的FTP端口记得也要填1666.

我这改了端口号的，也确实不行
![Snipaste_2020-09-27_19-49-51](https://user-images.githubusercontent.com/44677306/94364272-a087a400-00fa-11eb-9e8e-b96dc9d1c67f.png)
