### ISSUE TITLE
请问要卸载官方源码自带的dnsmasq，换成dnsmasq-full，我需要在哪里修改

### ISSUE THREAD

**Issue by 1164715233** [garypang13/Actions-OpenWrt#149]
config里面不成功，sh里修改会更好吗？

**Comment by garypang13** [comment]
就是在config里,

**Comment by 1164715233** [comment]
> 就是在config里,

我拉取的是v19.07.4的源码，不知道为什么编译4次都是dnsmasq出错，我再研究一下吧😄

**Comment by garypang13** [comment]
我的就是官方源码,默认就是换成dnsmasq-full了的,直接在我的基础上改改就行,没必要从零折腾,
