### ISSUE TITLE
Turbo ACC DNS 缓存 无法自动启动，只能手动启动

### ISSUE THREAD

**Issue by moxuanyuan** [garypang13/Actions-OpenWrt#154]
K2P，已经刷了最新的10.7固件，之前的都刷过，同样的问题，就是重启后，DNS  缓存 不能启动，只能手动启动（就是在设置页面保存并应用）。
恢复出厂设置也没有用。把SSRP关了也是不能启动。。。

**Comment by garypang13** [comment]
已修复.
