### ISSUE TITLE
x86 版本，防火墙 端口转发  怎么保存后 就没有了

### ISSUE THREAD

**Issue by lkddi** [garypang13/Actions-OpenWrt#156]
新建端口转发后，保存后就消失了。

**Comment by lkddi** [comment]
![image](https://user-images.githubusercontent.com/1597780/95547845-6beae500-0a36-11eb-9b82-81050c09cd87.png)

![image](https://user-images.githubusercontent.com/1597780/95547859-760ce380-0a36-11eb-8126-86076994c5af.png)


![image](https://user-images.githubusercontent.com/1597780/95547870-7c9b5b00-0a36-11eb-9574-dffa3a511f73.png)

**Comment by garypang13** [comment]
我刚测试了,并未出现你说的这情况

![image](https://user-images.githubusercontent.com/48883331/95548057-df8cf200-0a36-11eb-9c11-1be5a6442426.png)

**Comment by lkddi** [comment]
点击保存并应用，就没有了

**Comment by garypang13** [comment]
点击保存并应用依然在,另外转发里默认应该有些规则的,
