### ISSUE TITLE
X86_64 编译OAF的问题

### ISSUE THREAD

**Issue by bingxueqingzhi** [garypang13/Actions-OpenWrt#171]
.config里, CONFIG_PACKAGE_luci-app-oaf=y
但似乎并没有编译进去, 网页UI里看不到OAF的页面

**Comment by garypang13** [comment]
是luci-app-appfilter而不是luci-app-oaf

**Comment by bingxueqingzhi** [comment]
> 
> 
> 是luci-app-appfilter而不是luci-app-oaf

那OAF是?

**Comment by garypang13** [comment]
刚改成了luci-app-oaf了,重新拉取下代码

**Comment by bingxueqingzhi** [comment]
> 
> 
> 刚改成了luci-app-oaf了,重新拉取下代码

好的,感谢
