### ISSUE TITLE
大佬你好，今天下了你的r2s的rom，一直都没折腾好，解压出来是80M的11.01-openwrt-rockchip-armv8-nanopi-r2s-squashfs-sysupgrade.img文件没错吧，这是完整版的刷机包，或者知识升级包？

### ISSUE THREAD

**Issue by watergenie51** [garypang13/Actions-OpenWrt#178]

**Comment by garypang13** [comment]
是完整的包.靠近电源口的是WAN口

**Comment by jerrykkkkk** [comment]
我也是这样，感觉没刷成功一样，用Win32DiskImager和balenaEtcher软件刷了12.28-openwrt-rockchip-armv8-nanopi-r2s-squashfs-sysupgrade.img.gz固件，接入电源后，sys灯常亮，wan口 lan口连接电脑都没反应。是我操作不对么？

**Comment by garypang13** [comment]
r2s比较挑固件的,如果不成功就只能换固件.
