### ISSUE TITLE
请问下如何给放到files里面的文件修改权限

### ISSUE THREAD

**Issue by yhl452493373** [garypang13/Actions-OpenWrt#181]
我自己修改了脚本，打包了openclash，把clash，clash_tun和clash_game放到了files/etc/openclash/core里面，打包后固件里面确实也集成了，但是权限不对。我在default-setting和diy两个脚本都试过chmod，但是都没改权限。不知道我应该在哪里改权限以及用什么路径？

**Comment by garypang13** [comment]
源码中某文件权限是755,那在固件中此文件权限就会是755.

**Comment by yhl452493373** [comment]
> 源码中某文件权限是755,那在固件中此文件权限就会是755.

但是我是git传上去的，这个是默认的644吧？

**Comment by garypang13** [comment]
git push前需要使用 git update-index --chmod +x files/etc/openclash/core/xx.sh 增加写权限

**Comment by yhl452493373** [comment]
好的，多谢了🙏
