### ISSUE TITLE
今天编译报错啊

### ISSUE THREAD

**Issue by yhl452493373** [garypang13/Actions-OpenWrt#183]
<img width="958" alt="截屏2020-11-09 下午3 01 14" src="https://user-images.githubusercontent.com/26134687/98509642-86fe7e00-229c-11eb-80b5-9b7dfd941160.png">

卡在 Load custom configuration

**Comment by garypang13** [comment]
已修复.

**Comment by yhl452493373** [comment]
> 已修复.

感谢
