### ISSUE TITLE
R2S刷完LAN口连接电脑网卡灯不亮

### ISSUE THREAD

**Issue by liuyq917** [garypang13/Actions-OpenWrt#199]
大佬求助一下，R2S刷好后，LAN口连接电脑网卡灯不亮，WAN口（靠近电源的口）连接电脑网卡灯亮。换过您几个版本都是这样。刷过其他人的固件是正常的，所以硬件肯定是好的。不知道为什么。

**Comment by garypang13** [comment]
电源的问题,电压不够.
