### ISSUE TITLE
登录password

### ISSUE THREAD

**Issue by onewrt** [garypang13/Actions-OpenWrt#2]
老大，你固件登录密码是多少。试了password  admin这些都不是。

**Comment by garypang13** [comment]
139715jia,建议在zzz-default-settings中改成自己的.

**Comment by onewrt** [comment]
好的。还有个问题。我这边云编译成功后，在对release的时候，一直提示虚拟机失败。
![image](https://user-images.githubusercontent.com/59407795/75601971-b1881c80-5afb-11ea-8459-c604c9396ff7.png)

**Comment by garypang13** [comment]
encrypted secrets的权限都勾上试试.

**Comment by onewrt** [comment]
已经是全选的，我找了半天都zha找不出原因。所以求助于你。
![image](https://user-images.githubusercontent.com/59407795/75602901-80f8b080-5b04-11ea-9a6e-817976818caa.png)

**Comment by onewrt** [comment]
我在试试给目录权限。
