### ISSUE TITLE
R2S ppoe拨号不成功

### ISSUE THREAD

**Issue by ChristopherSung** [garypang13/Actions-OpenWrt#202]
光猫桥接 r2s 拨号失败  11.19和26号的版本都试过了

Fri Nov 27 22:44:38 2020 daemon.notice netifd: Interface 'wan' is now down
Fri Nov 27 22:44:38 2020 daemon.notice netifd: Interface 'wan' is setting up now
Fri Nov 27 22:44:38 2020 daemon.err insmod: module is already loaded - slhc
Fri Nov 27 22:44:38 2020 daemon.err insmod: module is already loaded - ppp_generic
Fri Nov 27 22:44:38 2020 daemon.err insmod: module is already loaded - pppox
Fri Nov 27 22:44:38 2020 daemon.err insmod: module is already loaded - pppoe
Fri Nov 27 22:44:38 2020 daemon.notice netifd: wan (19479): uci: Entry not found
Fri Nov 27 22:44:38 2020 daemon.notice netifd: wan (19479): sh: out of range
Fri Nov 27 22:44:38 2020 daemon.info pppd[19510]: Plugin rp-pppoe.so loaded.
Fri Nov 27 22:44:38 2020 daemon.info pppd[19510]: RP-PPPoE plugin version 3.8p compiled against pppd 2.4.8
Fri Nov 27 22:44:38 2020 daemon.notice pppd[19510]: pppd 2.4.8 started by root, uid 0

**Comment by jackadam1981** [comment]
试试改MTU为1492，我的联通线路改1492可以拨号，1500不能拨号，电信线路1500，1492都拨号不成功。

**Comment by ChristopherSung** [comment]
> 试试改MTU为1492，我的联通线路改1492可以拨号，1500不能拨号，电信线路1500，1492都拨号不成功。

感谢回复最后发现是mac地址的问题 运营商绑定了光猫的mac地址
