### ISSUE TITLE
WIF主题显示问题

### ISSUE THREAD

**Issue by zhaoyuhua520** [garypang13/Actions-OpenWrt#203]
![photo_2020-11-30_11-12-36](https://user-images.githubusercontent.com/46662238/100565018-7c646100-32fd-11eb-98ca-26c4f29d6606.jpg)
WIFI开启，但是不能使用

**Comment by Neverends4** [comment]
好像是luci-app-mtwifi-1.7的问题，1.0时没这个问题
我这边是不显示，但是你设置好了设备能连上无线………………
