### ISSUE TITLE
Phicomm K2P 升级到12.05.2020版本后 Wi-Fi无法启用

### ISSUE THREAD

**Issue by ideatechfr** [garypang13/Actions-OpenWrt#209]
你好！
今天系统刷到12.05.2020版本后，Wi-Fi功能不能启动显示已禁用，另外我尝试手动设置了新的信道，无线安全选项里只有无加密一个选项。麻烦看看是什么问题. 

谢谢

**Comment by ideatechfr** [comment]
更新到12.06.2020版本，Wi-Fi能激活使用

- 网络标签里有2个无线，第一个无线点击进入后显示设备未激活
![截屏2020-12-06 14 00 38](https://user-images.githubusercontent.com/37808758/101280814-84277800-37cb-11eb-977e-7d93c9aa9498.png)
- 访客网络功能无效，勾选启用及创建/删除 或单独勾选启用都发现不了访客网络

**Comment by garypang13** [comment]
把/etc/config/wireless这个文件删掉,第一个无线菜单就会消失了.

**Comment by ideatechfr** [comment]
> 把/etc/config/wireless这个文件删掉,第一个无线菜单就会消失了.

感谢，意思是把这个功能先屏蔽掉了，想知道这个功能在K2P上是否能正常运行？

**Comment by ideatechfr** [comment]
版本更新到 12.09.2020 Wi-Fi 5G不能激活，麻烦大佬看一下
![截屏2020-12-08 21 41 49](https://user-images.githubusercontent.com/37808758/101539570-05833400-399f-11eb-9751-92813908993e.png)

**Comment by garypang13** [comment]
@ideatechfr 5G设置个信道就好了,

**Comment by ideatechfr** [comment]
@garypang13 感谢大佬，麻烦问一下现在是刷12.06这个版本吗？（记得昨天看看到有个12.09这个版本）5g的问题把版本刷回到11.30了。

**Comment by garypang13** [comment]
@ideatechfr 我在重新编译,默认设置好信道,

**Comment by ideatechfr** [comment]
@garypang13 感谢!
