### ISSUE TITLE
中继已经成功,请问怎么断掉之后自动连接中继和重启以后自动连接中继

### ISSUE THREAD

**Issue by zrwd01** [garypang13/Actions-OpenWrt#210]
中继已经成功,请问怎么断掉之后自动连接中继和重启以后自动连接中继

**Comment by mlw221** [comment]
装个travelmate插件，能设置多个上级ap, 断网或重启后自动连接。

**Comment by zrwd01** [comment]
> 装个travelmate插件，能设置多个上级ap, 断网或重启后自动连接。

谢谢
