### ISSUE TITLE
Adblock plus的一些问题建议

### ISSUE THREAD

**Issue by WROIATE** [garypang13/Actions-OpenWrt#212]
很棒的插件，但有些问题或建议，希望能考虑解决下
1. 和网易云解锁似乎有冲突，在重启adblockplus后网易云解锁就无法启动了
2. 建议添加自动更新时间的范围，如每周一次而不是每天一次
3. 添加修改host的功能

**Comment by garypang13** [comment]
第一个问题我这边并没有出现,用的是luci-app-unblockmusic
第二个建议感觉没什么必要,规则更新几乎不占用资源,且每天更新一次是有必要的.
修改Hosts可以用 luci-app-advanced https://github.com/garypang13/openwrt-packages/tree/master/luci-app-advanced 或者dhcp中的自定义挟持域名能实现Hosts一样的效果

**Comment by WROIATE** [comment]
@garypang13 
奇怪了，我这的确网易云会无法启动，必须关掉adblockplus才能开启，而且我在两台路由，一个n1一个x86_64上都出现这个问题，顺带一提我还开了passwall。
修改host我是认为可以集成在其中，方便使用，并且在插件开启时修改，关闭时恢复
