### ISSUE TITLE
usb-c版本的r2s刷入无法启动

### ISSUE THREAD

**Issue by 2131411** [garypang13/Actions-OpenWrt#220]
用的大佬的编译好的r2s，从10.04版本刷到12.16。
试了wan口跟lan都提示无法识别网络，网络口的灯也不亮。
硬件：usb-c版本的r2s、商家提供的电源、闪迪16Gb（C10A1）

**Comment by garypang13** [comment]
@2131411 多刷几次试试,我自己的r2s刷12.16是没问题的.

**Comment by 2131411** [comment]
> @ 2131411多刷一次尝试，我自己的r2s刷12.16是没问题的。

不行，而且搜了一下好多人都是这个问题，都是tape-c接口的
