### ISSUE TITLE
20日的ssr+ 选择xray后配置界面有Bug

### ISSUE THREAD

**Issue by Tiga888** [garypang13/Actions-OpenWrt#221]
<img width="1440" alt="截屏2020-12-20 下午4 18 48" src="https://user-images.githubusercontent.com/75403044/102708721-85829580-42df-11eb-9ebd-e51cc2feb0e5.png">
自定义ws host的框在选择了启用tls后会消失，
<img width="1440" alt="截屏2020-12-20 下午4 19 02" src="https://user-images.githubusercontent.com/75403044/102708739-b793f780-42df-11eb-86af-91975a89171d.png">

**Comment by garypang13** [comment]
@Tiga888

**Comment by Tiga888** [comment]
我直接在地址里面设置域名，然后在hosts文件里面指向ip，可以解决这个问题。
