### ISSUE TITLE
可以加入对qca8171网卡的支持吗？

### ISSUE THREAD

**Issue by Tiga888** [garypang13/Actions-OpenWrt#224]
我用联想y410p当的软路由，自带的网卡是qca8171。默认编译的固件没有支持这个网卡，只需要在config里面加上network devices下面的kmod-alx就行了。我现在只能每次fork项目把这个选上在自己编译一遍。十分感谢！🙏

**Comment by garypang13** [comment]
@Tiga888 config中已添加,等下版编译.

**Comment by Tiga888** [comment]
感谢大佬

**Comment by garypang13** [comment]
新版固件已发布.
