### ISSUE TITLE
R2S固件无法安装USB网络共享和无线网卡

### ISSUE THREAD

**Issue by Brokentropy** [garypang13/Actions-OpenWrt#225]
大佬的固件做的很好, 在Openwrt上做了很多人性化的优化. 个人在使用中有一个痛点: 
需要在无网线上网的情况下测试R2S, 因此需要使用手机USB网络共享或者USB无线网卡
USB无线网卡, 手头只有小米随身WiFi, 芯片为mt7601u
在安装kmod-usb-net-rndis, kmod-usb-net-cdc-ether, 以及kmod-mt7601u的时候均提示内核不一致 (but incompatible with the architectures configured)
查看R2S固件和软件包的内核均为aarch64_generic, 所以实在不理解为什么提示内核不一致, 这几个软件包需要在固件中提前刷好吗?

**Comment by garypang13** [comment]
@Brokentropy 是的,需要编译固件的时候就加进去, 已在源码中增加相关代码的支持,请等下一版固件发布.

**Comment by Brokentropy** [comment]
@garypang13 原来是需要编译固件的时候加进去, 看了好多教程都是后期安装的(包括openwrt官网的), 折腾了一天也没成功. 等刷好下一版固件我再来回复

**Comment by garypang13** [comment]
新版固件已发布.

**Comment by Brokentropy** [comment]
@garypang13 大佬, R2S固件下载没发现今天的包, nanopi-r2s_sha256sums更新了, 但是固件包好像没更新😅😅

**Comment by garypang13** [comment]
@Brokentropy 有点问题下架了,已经重新发布.

**Comment by Brokentropy** [comment]
@garypang13 2z种方式都成功了, 完美😄😄😄
