### ISSUE TITLE
严重bug，无限重启

### ISSUE THREAD

**Issue by Omoinemie** [garypang13/Actions-OpenWrt#226]
我尝试在R2S上安装了几个插件：ddns，frps，serverchan，然后重启就进不了系统了。后来我又用x64虚拟机安装这几个插件测试，发现卡在开机，无线重启，是不是serverchan的原因？因为我一安装后路由器界面就提示会话过期要重新登录！

**Comment by Omoinemie** [comment]
原因找到，是安装了nlbwmon插件套装会导致无限重启

![Snipaste_2020-12-25_10-46-33](https://user-images.githubusercontent.com/31991443/103115695-9eec5e80-469e-11eb-8b01-9c61fea1e2d0.jpg)
![Snipaste_2020-12-25_10-46-56](https://user-images.githubusercontent.com/31991443/103115697-a01d8b80-469e-11eb-8706-ec8dc55f11e4.jpg)

**Comment by garypang13** [comment]
感谢测试, 插件的问题只能等插件作者修复了,

**Comment by Omoinemie** [comment]
你确定不是你的固件问题？
