### ISSUE TITLE
红米 ac2100 如何使用 guest-wifi？

### ISSUE THREAD

**Issue by jinglei207** [garypang13/Actions-OpenWrt#227]
看了以下设置，Define device 只能选 radio0， radio1...  这应该是给开源驱动的吧？

如果没卵用，下个版本就直接别加了吧。

**Comment by garypang13** [comment]
好的,

**Comment by jinglei207** [comment]
> 
> 
> 好的,

有办法设置 第二个 SSID 吗？ 弄了半天搞不定。

**Comment by jinglei207** [comment]
解决了，发现设置 BssidNum=2 的时候， web interface 会 多出来一个 AP，直接在那里开启了密码。
