### ISSUE TITLE
r2s固件请愿添加对cf811ac网卡的支持

### ISSUE THREAD

**Issue by heyhey997** [garypang13/Actions-OpenWrt#228]
如题，感觉大佬的插件很适合我，但手上只有comfast811ac的无线网卡，希望能添加对其支持

**Comment by garypang13** [comment]
你有测试过不支持么, 测试下这个固件支持不,https://github.com/QiuSimons/R2S-OpenWrt

**Comment by heyhey997** [comment]
嗯，把您和qiu大佬的都试了下 不支持cf811ac无线网卡 无线一栏同样显示设备未激活

**Comment by garypang13** [comment]
我不知道comfast811ac这个网卡openwrt有没有对应的驱动,有的话可以添加进去,没有的话也没办法.

**Comment by heyhey997** [comment]
感谢 费心了
