### ISSUE TITLE
右上角没有出现x86_64 Actions,K2P Actions等按钮

### ISSUE THREAD

**Issue by be-engineer** [garypang13/Actions-OpenWrt#233]
方式2: 请在支持油猴的浏览器中安装 脚本 ,仓库右上角会出现 x86_64 Actions,K2P Actions等按钮,点击对应按钮即可

已经安装了油猴脚本，但是没有这些按钮，是哪里需要设置吗？
只有Repo Dispatcher里有一个Run workflow按钮

**Comment by garypang13** [comment]
多刷新几次试试,
