### ISSUE TITLE
安装软件仓库的argon主题无效

### ISSUE THREAD

**Issue by poormonitor** [garypang13/Actions-OpenWrt#235]
安装软件仓库的argon主题后在系统中找不到配置argon的选项，使用github上发布的ipk无此问题。

**Comment by garypang13** [comment]
luci-app-argon

![image](https://user-images.githubusercontent.com/48883331/103434043-84822a00-4c36-11eb-9b75-5a289da1d5e8.png)

**Comment by poormonitor** [comment]
![image](https://user-images.githubusercontent.com/62340684/103436592-4138b300-4c58-11eb-9328-41f83eea243c.png)
此处

**Comment by garypang13** [comment]
@poormonitor 已修复,卸载后重装即可.
