### ISSUE TITLE
请在x64上添加binfmt支持, 谢谢.

### ISSUE THREAD

**Issue by radiocom** [garypang13/Actions-OpenWrt#237]
需要用到binfmt, 添加很简单,  CONFIG_BINFMT_MISC=y
参考: https://www.right.com.cn/forum/thread-4052047-1-1.html

理由:
我需要在docker里面跑x86的wine, 用Wine来运行windows版本的迅雷.
而且我发现有些人会需要跑Arm的docker. 相信很多人也会有同样的需求.
谢谢!

**Comment by garypang13** [comment]
@radiocom 源码中已添加支持,等下版固件发布.

**Comment by radiocom** [comment]
谢谢~
