### ISSUE TITLE
大佬SFE不太稳定能换回Flowoffload吗？

### ISSUE THREAD

**Issue by lzqd** [garypang13/Actions-OpenWrt#239]
大佬SFE不太稳定能换回Flowoffload吗？
周期性网络丢包和延时异常，关闭SFE后略好。

**Comment by garypang13** [comment]
@lzqd x86和r2s有编译sfe和flowoffload,可以在turboacc中选择,

**Comment by lzqd** [comment]
> @lzqd x86和r2s有编译sfe和flowoffload，可以在turboacc中选择，

在哪里？没找到！

**Comment by garypang13** [comment]
取消 Shortcut-FE 流量分载 后就能看到了,
![image](https://user-images.githubusercontent.com/48883331/103663902-9522ff00-4fac-11eb-994e-320058a8a014.png)

**Comment by lzqd** [comment]
> @lzqd x86和r2s有编译sfe和flowoffload，可以在turboacc中选择，

软件流量分载也存在周期丢包的问题，我重刷试试吧！
