### ISSUE TITLE
关于LAN口无法获取IPv6地址的问题

### ISSUE THREAD

**Issue by littlewhitelyw** [garypang13/Actions-OpenWrt#253]
各位好：
机型：`红米AC2100`
固件版本：`2021.01.12`

校园网环境，`WAN`口可正常获取`IPv6`地址，`SSH`进入路由器后可`ping`通`IPv6`。
但是`LAN`口无法获得`IPv6`地址，搜了各种教程，全都试过了还是不行，有没有配置成功的小伙伴，求教学

**Comment by littlewhitelyw** [comment]
已完成

**Comment by Heipen** [comment]
> 各位好： 机型：`红米AC2100` 固件版本：`2021.01.12`
> 
> 校园网环境，`WAN`口可正常获取`IPv6`地址，`SSH`进入路由器后可`ping`通`IPv6`。 但是`LAN`口无法获得`IPv6`地址，搜了各种教程，全都试过了还是不行，有没有配置成功的小伙伴，求教学

我也一直有同样的问题，能否请问下是怎么解决的？

**Comment by lywly** [comment]
> > 各位好： 机型：`红米AC2100` 固件版本：`2021.01.12`
> > 校园网环境，`WAN`口可正常获取`IPv6`地址，`SSH`进入路由器后可`ping`通`IPv6`。 但是`LAN`口无法获得`IPv6`地址，搜了各种教程，全都试过了还是不行，有没有配置成功的小伙伴，求教学
> 
> 我也一直有同样的问题，能否请问下是怎么解决的？

抱歉，时间太久忘记怎么配置的了，现在已经不玩路由器了。当时记录了一些信息在博客里，供你参考：[OpenWrt配置记录](https://lywly.cn/archives/151/)
