### ISSUE TITLE
release不了虚拟机固件

### ISSUE THREAD

**Issue by onewrt** [garypang13/Actions-OpenWrt#3]
老大，在麻烦下。打包出来的固件里含有虚拟机固件。所以不能release。这个有解吗？
![image](https://user-images.githubusercontent.com/59407795/75608253-e4043a80-5b38-11ea-8181-b8f7790cffd1.png)

另外一个没有虚拟机也relelease不了。
![image](https://user-images.githubusercontent.com/59407795/75608287-36455b80-5b39-11ea-86f6-229e38cd8483.png)

**Comment by garypang13** [comment]
完全用我的代码能正常release吗,我的只上传了openwrt-x86-64-combined-squashfs.img.gz,我用的就是虚拟机,只需要这个文件就够了,
